use crate::cond::{Cond, PropCheck};
use crate::rarity::Rarity;

pub struct Badge {
    pub id: &'static str,
    pub name: &'static str,
    pub desc: &'static str,
    pub condition: Cond,
    pub ep: u32,
    pub rarity: Rarity,
    pub icon: &'static str,
}

pub struct MemeEntry {
    pub number: u32,
    pub badge_id: &'static str,
}

pub const MEME_NUMBERS: &[MemeEntry] = &[
    MemeEntry {
        number: 0,
        badge_id: "zero",
    },
    MemeEntry {
        number: 1,
        badge_id: "one",
    },
    MemeEntry {
        number: 42,
        badge_id: "answer",
    },
    MemeEntry {
        number: 69,
        badge_id: "nice",
    },
    MemeEntry {
        number: 420,
        badge_id: "blaze_it",
    },
    MemeEntry {
        number: 666,
        badge_id: "number_of_the_beast",
    },
    MemeEntry {
        number: 777,
        badge_id: "jackpot",
    },
    MemeEntry {
        number: 1000,
        badge_id: "one_k",
    },
    MemeEntry {
        number: 1337,
        badge_id: "leet",
    },
    MemeEntry {
        number: 404,
        badge_id: "not_found",
    },
    MemeEntry {
        number: 80085,
        badge_id: "boobs",
    },
    MemeEntry {
        number: 100000,
        badge_id: "one_hundred_k",
    },
    MemeEntry {
        number: 123456,
        badge_id: "consecutive",
    },
    MemeEntry {
        number: 654321,
        badge_id: "reverse_consecutive",
    },
    MemeEntry {
        number: 111111,
        badge_id: "all_ones",
    },
    MemeEntry {
        number: 222222,
        badge_id: "all_twos",
    },
    MemeEntry {
        number: 333333,
        badge_id: "all_threes",
    },
    MemeEntry {
        number: 444444,
        badge_id: "all_fours",
    },
    MemeEntry {
        number: 555555,
        badge_id: "all_fives",
    },
    MemeEntry {
        number: 666666,
        badge_id: "all_sixes",
    },
    MemeEntry {
        number: 777777,
        badge_id: "all_sevens",
    },
    MemeEntry {
        number: 888888,
        badge_id: "all_eights",
    },
    MemeEntry {
        number: 999999,
        badge_id: "all_nines",
    },
    MemeEntry {
        number: 1000000,
        badge_id: "one_million",
    },
    MemeEntry {
        number: 314159,
        badge_id: "pi_approx",
    },
    MemeEntry {
        number: 271828,
        badge_id: "e_approx",
    },
    MemeEntry {
        number: 69420,
        badge_id: "nice_blaze",
    },
    MemeEntry {
        number: 911,
        badge_id: "emergency",
    },
    MemeEntry {
        number: 7,
        badge_id: "bond",
    },
    MemeEntry {
        number: 100,
        badge_id: "hundred",
    },
    MemeEntry {
        number: 101,
        badge_id: "intro_level",
    },
    MemeEntry {
        number: 123,
        badge_id: "sequential_123",
    },
    MemeEntry {
        number: 143,
        badge_id: "i_love_you",
    },
    MemeEntry {
        number: 314,
        badge_id: "pi_day",
    },
    MemeEntry {
        number: 520,
        badge_id: "love_chinese",
    },
    MemeEntry {
        number: 808,
        badge_id: "tr_808",
    },
    MemeEntry {
        number: 888,
        badge_id: "lucky_eights",
    },
    MemeEntry {
        number: 1024,
        badge_id: "programmers_k",
    },
    MemeEntry {
        number: 1234,
        badge_id: "basic_sequence",
    },
    MemeEntry {
        number: 1314,
        badge_id: "forever",
    },
    MemeEntry {
        number: 1437,
        badge_id: "love_forever",
    },
    MemeEntry {
        number: 1776,
        badge_id: "independence",
    },
    MemeEntry {
        number: 1969,
        badge_id: "moon_landing",
    },
    MemeEntry {
        number: 1984,
        badge_id: "big_brother",
    },
    MemeEntry {
        number: 1999,
        badge_id: "party_like",
    },
    MemeEntry {
        number: 2000,
        badge_id: "y2k",
    },
    MemeEntry {
        number: 2020,
        badge_id: "the_year",
    },
    MemeEntry {
        number: 2048,
        badge_id: "the_game",
    },
    MemeEntry {
        number: 4096,
        badge_id: "the_sequel",
    },
    MemeEntry {
        number: 9000,
        badge_id: "over_nine_thousand",
    },
    MemeEntry {
        number: 161803,
        badge_id: "golden_ratio",
    },
    MemeEntry {
        number: 8008135,
        badge_id: "boobies",
    },
    MemeEntry {
        number: 5318008,
        badge_id: "boobies_flip",
    },
    MemeEntry {
        number: 8675309,
        badge_id: "jenny",
    },
    MemeEntry {
        number: 187,
        badge_id: "murder",
    },
    MemeEntry {
        number: 200,
        badge_id: "ok",
    },
    MemeEntry {
        number: 304,
        badge_id: "not_modified",
    },
    MemeEntry {
        number: 400,
        badge_id: "bad_request",
    },
    MemeEntry {
        number: 403,
        badge_id: "forbidden",
    },
    MemeEntry {
        number: 451,
        badge_id: "fahrenheit",
    },
    MemeEntry {
        number: 500,
        badge_id: "server_error",
    },
    MemeEntry {
        number: 6969,
        badge_id: "double_nice",
    },
    MemeEntry {
        number: 11235,
        badge_id: "fibonacci_start",
    },
    MemeEntry {
        number: 12345,
        badge_id: "almost_consecutive",
    },
    MemeEntry {
        number: 54321,
        badge_id: "reverse_almost",
    },
    MemeEntry {
        number: 31337,
        badge_id: "eleet",
    },
    MemeEntry {
        number: 98765,
        badge_id: "descending",
    },
    MemeEntry {
        number: 42069,
        badge_id: "nice_blaze_2",
    },
    MemeEntry {
        number: 11111,
        badge_id: "five_ones",
    },
    MemeEntry {
        number: 22222,
        badge_id: "five_twos",
    },
    MemeEntry {
        number: 33333,
        badge_id: "five_threes",
    },
    MemeEntry {
        number: 44444,
        badge_id: "five_fours",
    },
    MemeEntry {
        number: 55555,
        badge_id: "five_fives",
    },
    MemeEntry {
        number: 66666,
        badge_id: "five_sixes",
    },
    MemeEntry {
        number: 77777,
        badge_id: "five_sevens",
    },
    MemeEntry {
        number: 88888,
        badge_id: "five_eights",
    },
    MemeEntry {
        number: 99999,
        badge_id: "five_nines",
    },
    MemeEntry {
        number: 8,
        badge_id: "infinity",
    },
    MemeEntry {
        number: 9,
        badge_id: "cloud_nine",
    },
    MemeEntry {
        number: 10,
        badge_id: "binary_day",
    },
    MemeEntry {
        number: 11,
        badge_id: "snake_eyes",
    },
    MemeEntry {
        number: 13,
        badge_id: "bakers_dozen",
    },
    MemeEntry {
        number: 16,
        badge_id: "sweet_sixteen",
    },
    MemeEntry {
        number: 21,
        badge_id: "blackjack",
    },
    MemeEntry {
        number: 22,
        badge_id: "catch",
    },
    MemeEntry {
        number: 23,
        badge_id: "number_23",
    },
    MemeEntry {
        number: 24,
        badge_id: "jack_bauer",
    },
    MemeEntry {
        number: 27,
        badge_id: "comeback",
    },
    MemeEntry {
        number: 32,
        badge_id: "freezing_point",
    },
    MemeEntry {
        number: 55,
        badge_id: "speed_limit",
    },
    MemeEntry {
        number: 64,
        badge_id: "kia_ora",
    },
    MemeEntry {
        number: 66,
        badge_id: "route_66",
    },
    MemeEntry {
        number: 99,
        badge_id: "maximum_effort",
    },
    MemeEntry {
        number: 111,
        badge_id: "repeater",
    },
    MemeEntry {
        number: 112,
        badge_id: "emergency_eu",
    },
    MemeEntry {
        number: 212,
        badge_id: "boiling_point",
    },
    MemeEntry {
        number: 222,
        badge_id: "triple_twos",
    },
    MemeEntry {
        number: 300,
        badge_id: "perfect_game",
    },
    MemeEntry {
        number: 333,
        badge_id: "angel",
    },
    MemeEntry {
        number: 360,
        badge_id: "full_circle",
    },
    MemeEntry {
        number: 365,
        badge_id: "days",
    },
    MemeEntry {
        number: 366,
        badge_id: "leap_year",
    },
    MemeEntry {
        number: 401,
        badge_id: "code_401",
    },
    MemeEntry {
        number: 402,
        badge_id: "code_402",
    },
    MemeEntry {
        number: 405,
        badge_id: "code_405",
    },
    MemeEntry {
        number: 411,
        badge_id: "directory",
    },
    MemeEntry {
        number: 418,
        badge_id: "code_418",
    },
    MemeEntry {
        number: 429,
        badge_id: "code_429",
    },
    MemeEntry {
        number: 502,
        badge_id: "code_502",
    },
    MemeEntry {
        number: 503,
        badge_id: "code_503",
    },
    MemeEntry {
        number: 512,
        badge_id: "bit_depth",
    },
    MemeEntry {
        number: 555,
        badge_id: "half_way",
    },
    MemeEntry {
        number: 711,
        badge_id: "convenience",
    },
    MemeEntry {
        number: 1138,
        badge_id: "thx",
    },
    MemeEntry {
        number: 256,
        badge_id: "half_life",
    },
];

pub static BADGES: &[Badge] = &[
    Badge {
        id: "prime",
        name: "Prime",
        desc: "Your number is prime",
        condition: Cond::Prop(PropCheck::IsPrime),
        ep: 10,
        rarity: Rarity::Common,
        icon: "🔢",
    },
    Badge {
        id: "palindrome",
        name: "Palindrome",
        desc: "Reads the same forwards and backwards",
        condition: Cond::Prop(PropCheck::IsPalindrome),
        ep: 10,
        rarity: Rarity::Common,
        icon: "🪞",
    },
    Badge {
        id: "double",
        name: "Double",
        desc: "Contains a pair of identical adjacent digits",
        condition: Cond::Prop(PropCheck::HasDouble),
        ep: 5,
        rarity: Rarity::Common,
        icon: "👯",
    },
    Badge {
        id: "high_sum",
        name: "High Sum",
        desc: "Digit sum is 40 or higher",
        condition: Cond::Prop(PropCheck::DigitSumGte(40)),
        ep: 10,
        rarity: Rarity::Common,
        icon: "📈",
    },
    Badge {
        id: "low_sum",
        name: "Low Sum",
        desc: "Digit sum is 5 or lower",
        condition: Cond::Prop(PropCheck::DigitSumLte(5)),
        ep: 10,
        rarity: Rarity::Common,
        icon: "📉",
    },
    Badge {
        id: "perfect_square",
        name: "Perfect Square",
        desc: "Your number is a perfect square",
        condition: Cond::Prop(PropCheck::IsPerfectSquare),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "🔲",
    },
    Badge {
        id: "fibonacci",
        name: "Fibonacci",
        desc: "Your number is in the Fibonacci sequence",
        condition: Cond::Prop(PropCheck::IsFibonacci),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🐚",
    },
    Badge {
        id: "power_of_two",
        name: "Power of Two",
        desc: "Your number is 2^n for some n",
        condition: Cond::Prop(PropCheck::IsPowerOfTwo),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "⚡",
    },
    Badge {
        id: "triangular",
        name: "Triangular",
        desc: "Your number is a triangular number",
        condition: Cond::Prop(PropCheck::IsTriangular),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "🔺",
    },
    Badge {
        id: "triple",
        name: "Triple",
        desc: "Contains a run of 3 identical digits",
        condition: Cond::Prop(PropCheck::HasTriple),
        ep: 20,
        rarity: Rarity::Uncommon,
        icon: "3️⃣",
    },
    Badge {
        id: "ascending_run",
        name: "Ascending Run",
        desc: "Has a run of 3+ strictly ascending digits",
        condition: Cond::Prop(PropCheck::MaxAscendingRunGte(3)),
        ep: 20,
        rarity: Rarity::Uncommon,
        icon: "🔼",
    },
    Badge {
        id: "descending_run",
        name: "Descending Run",
        desc: "Has a run of 3+ strictly descending digits",
        condition: Cond::Prop(PropCheck::MaxDescendingRunGte(3)),
        ep: 20,
        rarity: Rarity::Uncommon,
        icon: "🔽",
    },
    Badge {
        id: "short_palindrome_prime",
        name: "Short Palindrome Prime",
        desc: "A prime palindrome with 4 or fewer digits",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsPalindrome),
            Cond::Prop(PropCheck::DigitCountLte(4)),
        ]),
        ep: 35,
        rarity: Rarity::Uncommon,
        icon: "🪞🔢",
    },
    Badge {
        id: "palindrome_prime",
        name: "Palindrome Prime",
        desc: "A prime that reads the same forwards and backwards",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🪞",
    },
    Badge {
        id: "quad",
        name: "Quad",
        desc: "Contains a run of 4 identical digits",
        condition: Cond::Prop(PropCheck::HasQuad),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "4️⃣",
    },
    Badge {
        id: "all_same",
        name: "All the Same",
        desc: "Every digit is identical",
        condition: Cond::Prop(PropCheck::AllSame),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🔁",
    },
    Badge {
        id: "strictly_ascending",
        name: "Strictly Ascending",
        desc: "Each digit is greater than the last",
        condition: Cond::Prop(PropCheck::StrictlyAscending),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "📈📈",
    },
    Badge {
        id: "strictly_descending",
        name: "Strictly Descending",
        desc: "Each digit is less than the last",
        condition: Cond::Prop(PropCheck::StrictlyDescending),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "📉📉",
    },
    Badge {
        id: "digit_sum_54",
        name: "Max Sum",
        desc: "Digit sum is exactly 54 (999999)",
        condition: Cond::Prop(PropCheck::DigitSumEq(54)),
        ep: 70,
        rarity: Rarity::Rare,
        icon: "💯",
    },
    Badge {
        id: "leading_zeros_5",
        name: "Mostly Zeroes",
        desc: "5 leading zeros (00000X)",
        condition: Cond::Prop(PropCheck::LeadingZerosEq(5)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "0️⃣",
    },
    Badge {
        id: "fibonacci_prime",
        name: "Fibonacci Prime",
        desc: "Both a Fibonacci number and prime",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsFibonacci),
            Cond::Prop(PropCheck::IsPrime),
        ]),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🐚🔢",
    },
    Badge {
        id: "square_and_triangular",
        name: "Square & Triangular",
        desc: "Both a perfect square and triangular number",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPerfectSquare),
            Cond::Prop(PropCheck::IsTriangular),
        ]),
        ep: 70,
        rarity: Rarity::Rare,
        icon: "🔲🔺",
    },
    Badge {
        id: "quint",
        name: "Quint",
        desc: "Contains a run of 5 identical digits",
        condition: Cond::Prop(PropCheck::HasQuint),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "5️⃣",
    },
    Badge {
        id: "ascending_5",
        name: "Long Ascension",
        desc: "Has a run of 5+ strictly ascending digits",
        condition: Cond::Prop(PropCheck::MaxAscendingRunGte(5)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🔼🔼",
    },
    Badge {
        id: "descending_5",
        name: "Long Descension",
        desc: "Has a run of 5+ strictly descending digits",
        condition: Cond::Prop(PropCheck::MaxDescendingRunGte(5)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🔽🔽",
    },
    Badge {
        id: "palindrome_prime_6",
        name: "6-Digit Palindrome Prime",
        desc: "A 6-digit prime palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsPalindrome),
            Cond::Prop(PropCheck::DigitCountEq(6)),
        ]),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🪞🪞",
    },
    Badge {
        id: "triple_properties",
        name: "Triple Threat",
        desc: "Prime, palindrome, AND perfect square... wait, only prime+palindrome+fibonacci is possible. prime + fibonacci + palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsFibonacci),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 300,
        rarity: Rarity::Epic,
        icon: "🏆",
    },
    Badge {
        id: "sextuple",
        name: "Sextuple",
        desc: "All 6 digits are identical",
        condition: Cond::Prop(PropCheck::HasSextuple),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "6️⃣",
    },
    Badge {
        id: "full_ascending",
        name: "Full Ascension",
        desc: "All digits strictly ascending (123456 or shorter)",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::StrictlyAscending),
            Cond::Prop(PropCheck::DigitCountGte(6)),
        ]),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🔺🔺",
    },
    Badge {
        id: "full_descending",
        name: "Full Descension",
        desc: "All digits strictly descending (654321 or shorter)",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::StrictlyDescending),
            Cond::Prop(PropCheck::DigitCountGte(6)),
        ]),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🔻🔻",
    },
    Badge {
        id: "zero",
        name: "Zero",
        desc: "The void. Nothing.",
        condition: Cond::Prop(PropCheck::ContainsNumber(0)),
        ep: 100,
        rarity: Rarity::Uncommon,
        icon: "🕳️",
    },
    Badge {
        id: "one",
        name: "One",
        desc: "The loneliest number",
        condition: Cond::Prop(PropCheck::ContainsNumber(1)),
        ep: 50,
        rarity: Rarity::Common,
        icon: "1️⃣",
    },
    Badge {
        id: "answer",
        name: "The Answer",
        desc: "42: the answer to life, the universe, and everything",
        condition: Cond::Prop(PropCheck::ContainsNumber(42)),
        ep: 100,
        rarity: Rarity::Uncommon,
        icon: "🌍",
    },
    Badge {
        id: "nice",
        name: "Nice",
        desc: "69",
        condition: Cond::Prop(PropCheck::ContainsNumber(69)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "😏",
    },
    Badge {
        id: "blaze_it",
        name: "Blaze It",
        desc: "420",
        condition: Cond::Prop(PropCheck::ContainsNumber(420)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🔥",
    },
    Badge {
        id: "number_of_the_beast",
        name: "Number of the Beast",
        desc: "666",
        condition: Cond::Prop(PropCheck::ContainsNumber(666)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "😈",
    },
    Badge {
        id: "jackpot",
        name: "Jackpot",
        desc: "777: lucky sevens",
        condition: Cond::Prop(PropCheck::ContainsNumber(777)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🎰",
    },
    Badge {
        id: "one_k",
        name: "One K",
        desc: "1000",
        condition: Cond::Prop(PropCheck::ContainsNumber(1000)),
        ep: 50,
        rarity: Rarity::Common,
        icon: "1️⃣0️⃣0️⃣0️⃣",
    },
    Badge {
        id: "leet",
        name: "LEET",
        desc: "1337",
        condition: Cond::Prop(PropCheck::ContainsNumber(1337)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "💻",
    },
    Badge {
        id: "not_found",
        name: "Not Found",
        desc: "404: number not found",
        condition: Cond::Prop(PropCheck::ContainsNumber(404)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🚫",
    },
    Badge {
        id: "boobs",
        name: "Boobs",
        desc: "80085",
        condition: Cond::Prop(PropCheck::ContainsNumber(80085)),
        ep: 100,
        rarity: Rarity::Uncommon,
        icon: "🫠",
    },
    Badge {
        id: "one_hundred_k",
        name: "100K",
        desc: "100,000",
        condition: Cond::Prop(PropCheck::ContainsNumber(100000)),
        ep: 100,
        rarity: Rarity::Uncommon,
        icon: "💯",
    },
    Badge {
        id: "consecutive",
        name: "Consecutive",
        desc: "123456: perfectly sequential",
        condition: Cond::Prop(PropCheck::ContainsNumber(123456)),
        ep: 1000,
        rarity: Rarity::Legendary,
        icon: "🔢🔢",
    },
    Badge {
        id: "reverse_consecutive",
        name: "Reverse Consecutive",
        desc: "654321: perfectly reverse-sequential",
        condition: Cond::Prop(PropCheck::ContainsNumber(654321)),
        ep: 1000,
        rarity: Rarity::Legendary,
        icon: "🔢🔀",
    },
    Badge {
        id: "all_ones",
        name: "All Ones",
        desc: "111111",
        condition: Cond::Prop(PropCheck::ContainsNumber(111111)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "1️⃣1️⃣1️⃣",
    },
    Badge {
        id: "all_twos",
        name: "All Twos",
        desc: "222222",
        condition: Cond::Prop(PropCheck::ContainsNumber(222222)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "2️⃣2️⃣2️⃣",
    },
    Badge {
        id: "all_threes",
        name: "All Threes",
        desc: "333333",
        condition: Cond::Prop(PropCheck::ContainsNumber(333333)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "3️⃣3️⃣3️⃣",
    },
    Badge {
        id: "all_fours",
        name: "All Fours",
        desc: "444444",
        condition: Cond::Prop(PropCheck::ContainsNumber(444444)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "4️⃣4️⃣4️⃣",
    },
    Badge {
        id: "all_fives",
        name: "All Fives",
        desc: "555555",
        condition: Cond::Prop(PropCheck::ContainsNumber(555555)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "5️⃣5️⃣5️⃣",
    },
    Badge {
        id: "all_sixes",
        name: "All Sixes",
        desc: "666666",
        condition: Cond::Prop(PropCheck::ContainsNumber(666666)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "6️⃣6️⃣6️⃣",
    },
    Badge {
        id: "all_sevens",
        name: "All Sevens",
        desc: "777777",
        condition: Cond::Prop(PropCheck::ContainsNumber(777777)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "7️⃣7️⃣7️⃣",
    },
    Badge {
        id: "all_eights",
        name: "All Eights",
        desc: "888888",
        condition: Cond::Prop(PropCheck::ContainsNumber(888888)),
        ep: 2000,
        rarity: Rarity::Mythic,
        icon: "8️⃣8️⃣8️⃣",
    },
    Badge {
        id: "all_nines",
        name: "All Nines",
        desc: "999999: the mythic number",
        condition: Cond::Prop(PropCheck::ContainsNumber(999999)),
        ep: 10000,
        rarity: Rarity::Mythic,
        icon: "👹",
    },
    Badge {
        id: "one_million",
        name: "One Million",
        desc: "1,000,000: the absolute max",
        condition: Cond::Prop(PropCheck::ContainsNumber(1000000)),
        ep: 5000,
        rarity: Rarity::Mythic,
        icon: "🏆",
    },
    Badge {
        id: "pi_approx",
        name: "Pi",
        desc: "314159: first 6 digits of pi",
        condition: Cond::Prop(PropCheck::ContainsNumber(314159)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "π",
    },
    Badge {
        id: "e_approx",
        name: "e",
        desc: "271828: first 6 digits of Euler's number",
        condition: Cond::Prop(PropCheck::ContainsNumber(271828)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "e",
    },
    Badge {
        id: "nice_blaze",
        name: "Nice Blaze",
        desc: "69420: the ultimate meme",
        condition: Cond::Prop(PropCheck::ContainsNumber(69420)),
        ep: 3000,
        rarity: Rarity::Mythic,
        icon: "🔥😏",
    },
    Badge {
        id: "emergency",
        name: "Emergency",
        desc: "911",
        condition: Cond::Prop(PropCheck::ContainsNumber(911)),
        ep: 100,
        rarity: Rarity::Uncommon,
        icon: "🚨",
    },
    Badge {
        id: "bond",
        name: "Bond",
        desc: "007: licensed to thrill",
        condition: Cond::Prop(PropCheck::ContainsNumber(7)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🕵️",
    },
    Badge {
        id: "hundred",
        name: "Hundred",
        desc: "100: a perfect score",
        condition: Cond::Prop(PropCheck::ContainsNumber(100)),
        ep: 10,
        rarity: Rarity::Common,
        icon: "💯",
    },
    Badge {
        id: "intro_level",
        name: "Intro Level",
        desc: "101: the beginning",
        condition: Cond::Prop(PropCheck::ContainsNumber(101)),
        ep: 10,
        rarity: Rarity::Common,
        icon: "📚",
    },
    Badge {
        id: "sequential_123",
        name: "Easy As",
        desc: "123: as easy as...",
        condition: Cond::Prop(PropCheck::ContainsNumber(123)),
        ep: 15,
        rarity: Rarity::Common,
        icon: "🎵",
    },
    Badge {
        id: "i_love_you",
        name: "I Love You",
        desc: "143: pager code for I love you",
        condition: Cond::Prop(PropCheck::ContainsNumber(143)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "💕",
    },
    Badge {
        id: "pi_day",
        name: "Pi Day",
        desc: "314: March 14th",
        condition: Cond::Prop(PropCheck::ContainsNumber(314)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🥧",
    },
    Badge {
        id: "love_chinese",
        name: "Wǔ Èr Líng",
        desc: "520: I love you in Chinese",
        condition: Cond::Prop(PropCheck::ContainsNumber(520)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🇨🇳",
    },
    Badge {
        id: "tr_808",
        name: "TR-808",
        desc: "808: the beat machine that changed music",
        condition: Cond::Prop(PropCheck::ContainsNumber(808)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🥁",
    },
    Badge {
        id: "lucky_eights",
        name: "Lucky Eights",
        desc: "888: triple fortune",
        condition: Cond::Prop(PropCheck::ContainsNumber(888)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🧧",
    },
    Badge {
        id: "basic_sequence",
        name: "Basic Sequence",
        desc: "1234: that's the kind of combination an idiot would have on his luggage",
        condition: Cond::Prop(PropCheck::ContainsNumber(1234)),
        ep: 20,
        rarity: Rarity::Common,
        icon: "🔑",
    },
    Badge {
        id: "programmers_k",
        name: "Programmer's K",
        desc: "1024: a round number in base 2",
        condition: Cond::Prop(PropCheck::ContainsNumber(1024)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "💻",
    },
    Badge {
        id: "forever",
        name: "Forever",
        desc: "1314: yī shēng yī shì, a lifetime",
        condition: Cond::Prop(PropCheck::ContainsNumber(1314)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "💍",
    },
    Badge {
        id: "love_forever",
        name: "Love Forever",
        desc: "1437: I love you forever",
        condition: Cond::Prop(PropCheck::ContainsNumber(1437)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "💕",
    },
    Badge {
        id: "independence",
        name: "Independence",
        desc: "1776: we the people",
        condition: Cond::Prop(PropCheck::ContainsNumber(1776)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🇺🇸",
    },
    Badge {
        id: "moon_landing",
        name: "One Small Step",
        desc: "1969: one giant leap for mankind",
        condition: Cond::Prop(PropCheck::ContainsNumber(1969)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🌙",
    },
    Badge {
        id: "big_brother",
        name: "Big Brother",
        desc: "1984: Orwell was right",
        condition: Cond::Prop(PropCheck::ContainsNumber(1984)),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "👁️",
    },
    Badge {
        id: "party_like",
        name: "Party Like It's",
        desc: "1999: tonight we're gonna party",
        condition: Cond::Prop(PropCheck::ContainsNumber(1999)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🎉",
    },
    Badge {
        id: "y2k",
        name: "Y2K",
        desc: "2000: the world didn't end",
        condition: Cond::Prop(PropCheck::ContainsNumber(2000)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "💿",
    },
    Badge {
        id: "the_year",
        name: "The Year",
        desc: "2020: we don't talk about it",
        condition: Cond::Prop(PropCheck::ContainsNumber(2020)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "😷",
    },
    Badge {
        id: "the_game",
        name: "The Game",
        desc: "2048: just one more tile",
        condition: Cond::Prop(PropCheck::ContainsNumber(2048)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🎮",
    },
    Badge {
        id: "the_sequel",
        name: "The Sequel",
        desc: "4096: twice the fun",
        condition: Cond::Prop(PropCheck::ContainsNumber(4096)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🎮",
    },
    Badge {
        id: "over_nine_thousand",
        name: "Over 9000!",
        desc: "9000: IT'S OVER NINE THOUSAND!!!",
        condition: Cond::Prop(PropCheck::ContainsNumber(9000)),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "💪",
    },
    Badge {
        id: "boobies",
        name: "BOOBIES",
        desc: "8008135: calculator humor",
        condition: Cond::Prop(PropCheck::ContainsNumber(8008135)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🍈",
    },
    Badge {
        id: "boobies_flip",
        name: "BOOBIES (Flip)",
        desc: "5318008: turn your calculator upside down",
        condition: Cond::Prop(PropCheck::ContainsNumber(5318008)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🔄🍈",
    },
    Badge {
        id: "jenny",
        name: "Jenny",
        desc: "8675309: Tommy Tutone's finest",
        condition: Cond::Prop(PropCheck::ContainsNumber(8675309)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "📞",
    },
    Badge {
        id: "golden_ratio",
        name: "Golden Ratio",
        desc: "161803: phi, nature's favorite number",
        condition: Cond::Prop(PropCheck::ContainsNumber(161803)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🌀",
    },
    Badge {
        id: "composite",
        name: "Composite",
        desc: "Not prime, not 1, just vibing",
        condition: Cond::Prop(PropCheck::IsComposite),
        ep: 5,
        rarity: Rarity::Common,
        icon: "🧱",
    },
    Badge {
        id: "has_zero",
        name: "Zero Alert",
        desc: "Contains at least one zero",
        condition: Cond::Prop(PropCheck::HasZero),
        ep: 5,
        rarity: Rarity::Common,
        icon: "0️⃣",
    },
    Badge {
        id: "even",
        name: "Even Steven",
        desc: "Divisible by 2",
        condition: Cond::Prop(PropCheck::IsEven),
        ep: 5,
        rarity: Rarity::Common,
        icon: "✌️",
    },
    Badge {
        id: "odd",
        name: "Odd One Out",
        desc: "Not divisible by 2",
        condition: Cond::Prop(PropCheck::IsOdd),
        ep: 5,
        rarity: Rarity::Common,
        icon: "☝️",
    },
    Badge {
        id: "harshad",
        name: "Harshad",
        desc: "Divisible by its own digit sum",
        condition: Cond::Prop(PropCheck::IsHarshad),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "➗",
    },
    Badge {
        id: "has_seven",
        name: "Lucky Seven",
        desc: "Contains at least one 7",
        condition: Cond::Prop(PropCheck::HasSeven),
        ep: 20,
        rarity: Rarity::Uncommon,
        icon: "7️⃣",
    },
    Badge {
        id: "no_zeros",
        name: "Zero Free",
        desc: "Not a single zero in sight",
        condition: Cond::Prop(PropCheck::NoZeros),
        ep: 20,
        rarity: Rarity::Uncommon,
        icon: "🚫",
    },
    Badge {
        id: "perfect_cube",
        name: "Perfect Cube",
        desc: "n = k\u{00b3} for some k",
        condition: Cond::Prop(PropCheck::IsPerfectCube),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🧊",
    },
    Badge {
        id: "happy",
        name: "Happy Number",
        desc: "Sum of squared digits eventually reaches 1",
        condition: Cond::Prop(PropCheck::IsHappy),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "😊",
    },
    Badge {
        id: "alternating",
        name: "Alternating",
        desc: "Digits alternate odd, even, odd, even...",
        condition: Cond::Prop(PropCheck::IsAlternating),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "↕️",
    },
    Badge {
        id: "contains_123",
        name: "It's In There",
        desc: "Contains 1-2-3 in sequence",
        condition: Cond::Prop(PropCheck::Has123),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "🔢",
    },
    Badge {
        id: "contains_666",
        name: "The Mark",
        desc: "Contains 6-6-6 in sequence",
        condition: Cond::Prop(PropCheck::Has666),
        ep: 70,
        rarity: Rarity::Rare,
        icon: "😈",
    },
    Badge {
        id: "factorial",
        name: "Factorial",
        desc: "n = k! for some k",
        condition: Cond::Prop(PropCheck::IsFactorial),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "❗",
    },
    Badge {
        id: "automorphic",
        name: "Automorphic",
        desc: "n\u{00b2} ends in n",
        condition: Cond::Prop(PropCheck::IsAutomorphic),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🪞",
    },
    Badge {
        id: "armstrong",
        name: "Armstrong",
        desc: "Narcissistic number: digits raised to power of digit count sum to n",
        condition: Cond::Prop(PropCheck::IsArmstrong),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "💪",
    },
    Badge {
        id: "big_product",
        name: "Big Product",
        desc: "Digit product is 100 or more",
        condition: Cond::Prop(PropCheck::DigitProductGte(100)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "✖️",
    },
    Badge {
        id: "digit_sum_square",
        name: "Square Sum",
        desc: "Digit sum is a perfect square",
        condition: Cond::Prop(PropCheck::DigitSumIsSquare),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "✨",
    },
    Badge {
        id: "no_repeats",
        name: "All Unique",
        desc: "No repeated digits",
        condition: Cond::Prop(PropCheck::NoRepeats),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🦄",
    },
    Badge {
        id: "prime_plus_even",
        name: "The Only Even Prime",
        desc: "Prime AND even: that's just 2",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsEven),
        ]),
        ep: 1000,
        rarity: Rarity::Legendary,
        icon: "🦄",
    },
    Badge {
        id: "fibonacci_even",
        name: "Even Fibonacci",
        desc: "Both a Fibonacci number and even",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsFibonacci),
            Cond::Prop(PropCheck::IsEven),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🐚✌️",
    },
    Badge {
        id: "palindrome_even",
        name: "Even Palindrome",
        desc: "A palindrome that's also even",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPalindrome),
            Cond::Prop(PropCheck::IsEven),
        ]),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🪞✌️",
    },
    Badge {
        id: "prime_harshad",
        name: "Harshad Prime",
        desc: "A prime that's divisible by its digit sum",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsHarshad),
        ]),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "🔢➗",
    },
    Badge {
        id: "happy_prime",
        name: "Happy Prime",
        desc: "A prime that's also a happy number",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsHappy),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "😊🔢",
    },
    Badge {
        id: "cube_palindrome",
        name: "Cube Palindrome",
        desc: "A perfect cube that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPerfectCube),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🧊🪞",
    },
    Badge {
        id: "murder",
        name: "187",
        desc: "187: police code for murder",
        condition: Cond::Prop(PropCheck::ContainsNumber(187)),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🔫",
    },
    Badge {
        id: "ok",
        name: "200 OK",
        desc: "200: everything is fine",
        condition: Cond::Prop(PropCheck::ContainsNumber(200)),
        ep: 15,
        rarity: Rarity::Common,
        icon: "✅",
    },
    Badge {
        id: "not_modified",
        name: "304",
        desc: "304: use what you've got",
        condition: Cond::Prop(PropCheck::ContainsNumber(304)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "📦",
    },
    Badge {
        id: "bad_request",
        name: "400",
        desc: "400: you messed up",
        condition: Cond::Prop(PropCheck::ContainsNumber(400)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "❌",
    },
    Badge {
        id: "forbidden",
        name: "403",
        desc: "403: you shall not pass",
        condition: Cond::Prop(PropCheck::ContainsNumber(403)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🚫",
    },
    Badge {
        id: "fahrenheit",
        name: "Fahrenheit",
        desc: "451: paper burns",
        condition: Cond::Prop(PropCheck::ContainsNumber(451)),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🔥",
    },
    Badge {
        id: "server_error",
        name: "500",
        desc: "500: it's not you, it's me",
        condition: Cond::Prop(PropCheck::ContainsNumber(500)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "💥",
    },
    Badge {
        id: "double_nice",
        name: "Double Nice",
        desc: "6969: nice nice",
        condition: Cond::Prop(PropCheck::ContainsNumber(6969)),
        ep: 300,
        rarity: Rarity::Epic,
        icon: "😏😏",
    },
    Badge {
        id: "fibonacci_start",
        name: "Fibonacci Start",
        desc: "11235: 1, 1, 2, 3, 5...",
        condition: Cond::Prop(PropCheck::ContainsNumber(11235)),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🐚",
    },
    Badge {
        id: "almost_consecutive",
        name: "Almost Consecutive",
        desc: "12345: so close",
        condition: Cond::Prop(PropCheck::ContainsNumber(12345)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🔢",
    },
    Badge {
        id: "reverse_almost",
        name: "Reverse Almost",
        desc: "54321: countdown",
        condition: Cond::Prop(PropCheck::ContainsNumber(54321)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "⏪",
    },
    Badge {
        id: "eleet",
        name: "31337",
        desc: "31337: el33t speak",
        condition: Cond::Prop(PropCheck::ContainsNumber(31337)),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🥷",
    },
    Badge {
        id: "descending",
        name: "Descending",
        desc: "98765: 9, 8, 7, 6, 5",
        condition: Cond::Prop(PropCheck::ContainsNumber(98765)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "⬇️",
    },
    Badge {
        id: "nice_blaze_2",
        name: "Nice Blaze 2.0",
        desc: "42069: the sequel nobody asked for",
        condition: Cond::Prop(PropCheck::ContainsNumber(42069)),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🔥😏",
    },
    Badge {
        id: "five_ones",
        name: "Five Ones",
        desc: "11111",
        condition: Cond::Prop(PropCheck::ContainsNumber(11111)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "1️⃣1️⃣1️⃣1️⃣1️⃣",
    },
    Badge {
        id: "five_twos",
        name: "Five Twos",
        desc: "22222",
        condition: Cond::Prop(PropCheck::ContainsNumber(22222)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "2️⃣2️⃣2️⃣2️⃣2️⃣",
    },
    Badge {
        id: "five_threes",
        name: "Five Threes",
        desc: "33333",
        condition: Cond::Prop(PropCheck::ContainsNumber(33333)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "3️⃣3️⃣3️⃣3️⃣3️⃣",
    },
    Badge {
        id: "five_fours",
        name: "Five Fours",
        desc: "44444",
        condition: Cond::Prop(PropCheck::ContainsNumber(44444)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "4️⃣4️⃣4️⃣4️⃣4️⃣",
    },
    Badge {
        id: "five_fives",
        name: "Five Fives",
        desc: "55555",
        condition: Cond::Prop(PropCheck::ContainsNumber(55555)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "5️⃣5️⃣5️⃣5️⃣5️⃣",
    },
    Badge {
        id: "five_sixes",
        name: "Five Sixes",
        desc: "66666",
        condition: Cond::Prop(PropCheck::ContainsNumber(66666)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "6️⃣6️⃣6️⃣6️⃣6️⃣",
    },
    Badge {
        id: "five_sevens",
        name: "Five Sevens",
        desc: "77777",
        condition: Cond::Prop(PropCheck::ContainsNumber(77777)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "7️⃣7️⃣7️⃣7️⃣7️⃣",
    },
    Badge {
        id: "five_eights",
        name: "Five Eights",
        desc: "88888",
        condition: Cond::Prop(PropCheck::ContainsNumber(88888)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "8️⃣8️⃣8️⃣8️⃣8️⃣",
    },
    Badge {
        id: "five_nines",
        name: "Five Nines",
        desc: "99999: the nines before the nines",
        condition: Cond::Prop(PropCheck::ContainsNumber(99999)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "9️⃣9️⃣9️⃣9️⃣9️⃣",
    },
    Badge {
        id: "evil",
        name: "Evil",
        desc: "Even number of 1s in binary",
        condition: Cond::Prop(PropCheck::IsEvil),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "👿",
    },
    Badge {
        id: "odious",
        name: "Odious",
        desc: "Odd number of 1s in binary",
        condition: Cond::Prop(PropCheck::IsOdious),
        ep: 25,
        rarity: Rarity::Uncommon,
        icon: "😈",
    },
    Badge {
        id: "pernicious",
        name: "Pernicious",
        desc: "Count of 1s in binary is prime",
        condition: Cond::Prop(PropCheck::IsPernicious),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "☠️",
    },
    Badge {
        id: "perfect_number",
        name: "Perfect Number",
        desc: "Sum of divisors equals n (6, 28, 496, 8128)",
        condition: Cond::Prop(PropCheck::IsPerfectNum),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "💎",
    },
    Badge {
        id: "abundant",
        name: "Abundant",
        desc: "Sum of divisors exceeds n",
        condition: Cond::Prop(PropCheck::IsAbundant),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "📈",
    },
    Badge {
        id: "deficient",
        name: "Deficient",
        desc: "Sum of divisors is less than n",
        condition: Cond::Prop(PropCheck::IsDeficient),
        ep: 5,
        rarity: Rarity::Common,
        icon: "📉",
    },
    Badge {
        id: "pronic",
        name: "Pronic",
        desc: "Product of two consecutive integers (n = k\u{00d7}(k+1))",
        condition: Cond::Prop(PropCheck::IsPronic),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "⬜",
    },
    Badge {
        id: "lucas",
        name: "Lucas",
        desc: "In the Lucas sequence (2, 1, 3, 4, 7, 11, ...)",
        condition: Cond::Prop(PropCheck::IsLucas),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🔢",
    },
    Badge {
        id: "undulating",
        name: "Undulating",
        desc: "Digits alternate between two digits (like 121212)",
        condition: Cond::Prop(PropCheck::IsUndulating),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🌊",
    },
    Badge {
        id: "moran",
        name: "Moran",
        desc: "Harshad number where n/digit_sum is prime",
        condition: Cond::Prop(PropCheck::IsMoran),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "🔢➗",
    },
    Badge {
        id: "semiprime",
        name: "Semiprime",
        desc: "Product of exactly two primes",
        condition: Cond::Prop(PropCheck::IsSemiprime),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "✖️",
    },
    Badge {
        id: "squarefree",
        name: "Squarefree",
        desc: "No prime factor appears more than once",
        condition: Cond::Prop(PropCheck::IsSquarefree),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🆓",
    },
    Badge {
        id: "smith",
        name: "Smith",
        desc: "Composite where digit sum equals sum of digits of prime factors",
        condition: Cond::Prop(PropCheck::IsSmith),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "🔨",
    },
    Badge {
        id: "lucky_prime",
        name: "Lucky Prime",
        desc: "A prime containing the digit 7",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::HasSeven),
        ]),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🍀",
    },
    Badge {
        id: "evil_prime",
        name: "Evil Prime",
        desc: "A prime with even binary ones",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPrime),
            Cond::Prop(PropCheck::IsEvil),
        ]),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "👿🔢",
    },
    Badge {
        id: "abundant_prime",
        name: "Abundant Composite",
        desc: "An abundant number that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsAbundant),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "📈🪞",
    },
    Badge {
        id: "semiprime_palindrome",
        name: "Semiprime Palindrome",
        desc: "A semiprime that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsSemiprime),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 120,
        rarity: Rarity::Rare,
        icon: "✖️🪞",
    },
    Badge {
        id: "happy_semiprime",
        name: "Happy Semiprime",
        desc: "A semiprime that's also happy",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsSemiprime),
            Cond::Prop(PropCheck::IsHappy),
        ]),
        ep: 120,
        rarity: Rarity::Rare,
        icon: "😊✖️",
    },
    // ── New math property badges ────────────────────────────────────
    Badge {
        id: "kaprekar",
        name: "Kaprekar",
        desc: "n\u{00b2} can be split into two parts that sum to n",
        condition: Cond::Prop(PropCheck::IsKaprekar),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "✂️",
    },
    Badge {
        id: "munchausen",
        name: "Munchausen",
        desc: "Sum of each digit raised to itself equals n (only 4 exist)",
        condition: Cond::Prop(PropCheck::IsMunchausen),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🎩",
    },
    Badge {
        id: "mersenne",
        name: "Mersenne",
        desc: "n = 2^p \u{2212} 1 for some prime p",
        condition: Cond::Prop(PropCheck::IsMersenne),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "🇲",
    },
    Badge {
        id: "power_of_ten",
        name: "Power of Ten",
        desc: "10, 100, 1000... a round number indeed",
        condition: Cond::Prop(PropCheck::IsPowerOfTen),
        ep: 50,
        rarity: Rarity::Uncommon,
        icon: "🔟",
    },
    Badge {
        id: "sphenic",
        name: "Sphenic",
        desc: "Product of exactly three distinct primes",
        condition: Cond::Prop(PropCheck::IsSphenic),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "🔺",
    },
    Badge {
        id: "dudeney",
        name: "Dudeney",
        desc: "Digit sum of n\u{00b3} equals n (only 6 exist)",
        condition: Cond::Prop(PropCheck::IsDudeney),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🧩",
    },
    Badge {
        id: "pentagonal",
        name: "Pentagonal",
        desc: "n = k(3k\u{2212}1)/2 for some k",
        condition: Cond::Prop(PropCheck::IsPentagonal),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "⬠",
    },
    Badge {
        id: "all_even",
        name: "All Even",
        desc: "Every digit is even",
        condition: Cond::Prop(PropCheck::AllEven),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "✌️✌️",
    },
    Badge {
        id: "all_odd",
        name: "All Odd",
        desc: "Every digit is odd",
        condition: Cond::Prop(PropCheck::AllOdd),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "1️⃣3️⃣5️⃣",
    },
    // ── New meme-number badges ──────────────────────────────────────
    Badge {
        id: "bakers_dozen",
        name: "Baker's Dozen",
        desc: "13 \u{2014} the baker's bonus",
        condition: Cond::Prop(PropCheck::ContainsNumber(13)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🥐",
    },
    Badge {
        id: "catch",
        name: "Catch",
        desc: "22 \u{2014} two little ducks",
        condition: Cond::Prop(PropCheck::ContainsNumber(22)),
        ep: 25,
        rarity: Rarity::Common,
        icon: "🦆",
    },
    Badge {
        id: "number_23",
        name: "The Number",
        desc: "23 \u{2014} the enigma",
        condition: Cond::Prop(PropCheck::ContainsNumber(23)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "🏀",
    },
    Badge {
        id: "jack_bauer",
        name: "Jack Bauer",
        desc: "24 \u{2014} the longest day",
        condition: Cond::Prop(PropCheck::ContainsNumber(24)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "⏰",
    },
    Badge {
        id: "perfect_game",
        name: "Perfect Game",
        desc: "300 \u{2014} a perfect score in bowling",
        condition: Cond::Prop(PropCheck::ContainsNumber(300)),
        ep: 60,
        rarity: Rarity::Rare,
        icon: "🎳",
    },
    Badge {
        id: "angel",
        name: "Angel",
        desc: "333 \u{2014} guardian angel number",
        condition: Cond::Prop(PropCheck::ContainsNumber(333)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "👼",
    },
    Badge {
        id: "infinity",
        name: "Sideways",
        desc: "8 \u{2014} looks like \u{221e} on its side",
        condition: Cond::Prop(PropCheck::ContainsNumber(8)),
        ep: 20,
        rarity: Rarity::Common,
        icon: "♾️",
    },
    Badge {
        id: "cloud_nine",
        name: "Cloud Nine",
        desc: "9 \u{2014} on cloud nine",
        condition: Cond::Prop(PropCheck::ContainsNumber(9)),
        ep: 20,
        rarity: Rarity::Common,
        icon: "☁️",
    },
    Badge {
        id: "binary_day",
        name: "Binary Day",
        desc: "10 \u{2014} it's binary for 2",
        condition: Cond::Prop(PropCheck::ContainsNumber(10)),
        ep: 20,
        rarity: Rarity::Common,
        icon: "💻",
    },
    Badge {
        id: "sweet_sixteen",
        name: "Sweet Sixteen",
        desc: "16 \u{2014} coming of age",
        condition: Cond::Prop(PropCheck::ContainsNumber(16)),
        ep: 25,
        rarity: Rarity::Common,
        icon: "🎂",
    },
    Badge {
        id: "comeback",
        name: "Comeback",
        desc: "27 \u{2014} the club legend",
        condition: Cond::Prop(PropCheck::ContainsNumber(27)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "⚽",
    },
    Badge {
        id: "blackjack",
        name: "Blackjack",
        desc: "21 \u{2014} hit me",
        condition: Cond::Prop(PropCheck::ContainsNumber(21)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🃏",
    },
    Badge {
        id: "snake_eyes",
        name: "Snake Eyes",
        desc: "11 \u{2014} roll the dice",
        condition: Cond::Prop(PropCheck::ContainsNumber(11)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🎲",
    },
    Badge {
        id: "repeater",
        name: "Repeater",
        desc: "111 \u{2014} make a wish",
        condition: Cond::Prop(PropCheck::ContainsNumber(111)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "✨",
    },
    Badge {
        id: "triple_twos",
        name: "Triple Twos",
        desc: "222 \u{2014} triple the twos",
        condition: Cond::Prop(PropCheck::ContainsNumber(222)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "2️⃣2️⃣2️⃣",
    },
    Badge {
        id: "half_way",
        name: "Halfway",
        desc: "555 \u{2014} the number sandwich",
        condition: Cond::Prop(PropCheck::ContainsNumber(555)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🥪",
    },
    Badge {
        id: "emergency_eu",
        name: "Euro Emergency",
        desc: "112 \u{2014} EU emergency number",
        condition: Cond::Prop(PropCheck::ContainsNumber(112)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🇪🇺",
    },
    Badge {
        id: "directory",
        name: "Directory",
        desc: "411 \u{2014} information please",
        condition: Cond::Prop(PropCheck::ContainsNumber(411)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "📖",
    },
    Badge {
        id: "kia_ora",
        name: "Kia Ora",
        desc: "64 \u{2014} New Zealand's calling code",
        condition: Cond::Prop(PropCheck::ContainsNumber(64)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🇳🇿",
    },
    Badge {
        id: "maximum_effort",
        name: "Max Effort",
        desc: "99 \u{2014} just shy of perfect",
        condition: Cond::Prop(PropCheck::ContainsNumber(99)),
        ep: 25,
        rarity: Rarity::Common,
        icon: "💯",
    },
    Badge {
        id: "boiling_point",
        name: "Boiling Point",
        desc: "212 \u{2014} water boils at 212\u{00b0}F",
        condition: Cond::Prop(PropCheck::ContainsNumber(212)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "🌡️",
    },
    Badge {
        id: "freezing_point",
        name: "Freezing Point",
        desc: "32 \u{2014} water freezes at 32\u{00b0}F",
        condition: Cond::Prop(PropCheck::ContainsNumber(32)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🧊",
    },
    Badge {
        id: "speed_limit",
        name: "Speed Limit",
        desc: "55 \u{2014} double nickel",
        condition: Cond::Prop(PropCheck::ContainsNumber(55)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "🚗",
    },
    Badge {
        id: "route_66",
        name: "Route 66",
        desc: "66 \u{2014} get your kicks",
        condition: Cond::Prop(PropCheck::ContainsNumber(66)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🛣️",
    },
    Badge {
        id: "half_life",
        name: "Half-Life",
        desc: "256 \u{2014} 2\u{2078}, the byte boundary",
        condition: Cond::Prop(PropCheck::ContainsNumber(256)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "☢️",
    },
    Badge {
        id: "bit_depth",
        name: "Bit Depth",
        desc: "512 \u{2014} 2\u{2079}, half a kilobyte",
        condition: Cond::Prop(PropCheck::ContainsNumber(512)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "💾",
    },
    Badge {
        id: "thx",
        name: "THX",
        desc: "1138 \u{2014} George Lucas's first film",
        condition: Cond::Prop(PropCheck::ContainsNumber(1138)),
        ep: 80,
        rarity: Rarity::Epic,
        icon: "🎬",
    },
    Badge {
        id: "full_circle",
        name: "Full Circle",
        desc: "360 \u{2014} degrees in a circle",
        condition: Cond::Prop(PropCheck::ContainsNumber(360)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🔄",
    },
    Badge {
        id: "days",
        name: "Calendar",
        desc: "365 \u{2014} days in a year",
        condition: Cond::Prop(PropCheck::ContainsNumber(365)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "📅",
    },
    Badge {
        id: "leap_year",
        name: "Leap Year",
        desc: "366 \u{2014} once every four years",
        condition: Cond::Prop(PropCheck::ContainsNumber(366)),
        ep: 50,
        rarity: Rarity::Rare,
        icon: "🐸",
    },
    Badge {
        id: "convenience",
        name: "Convenience",
        desc: "711 \u{2014} the store that's always open",
        condition: Cond::Prop(PropCheck::ContainsNumber(711)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🏪",
    },
    Badge {
        id: "code_401",
        name: "Unauthorized",
        desc: "401 \u{2014} you need to log in",
        condition: Cond::Prop(PropCheck::ContainsNumber(401)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🔐",
    },
    Badge {
        id: "code_402",
        name: "Payment Required",
        desc: "402 \u{2014} show me the money",
        condition: Cond::Prop(PropCheck::ContainsNumber(402)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "💳",
    },
    Badge {
        id: "code_405",
        name: "Method Not Allowed",
        desc: "405 \u{2014} you can't do that",
        condition: Cond::Prop(PropCheck::ContainsNumber(405)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🚷",
    },
    Badge {
        id: "code_418",
        name: "I'm a Teapot",
        desc: "418 \u{2014} I refuse to brew coffee",
        condition: Cond::Prop(PropCheck::ContainsNumber(418)),
        ep: 100,
        rarity: Rarity::Epic,
        icon: "🫖",
    },
    Badge {
        id: "code_429",
        name: "Slow Down",
        desc: "429 \u{2014} too many requests",
        condition: Cond::Prop(PropCheck::ContainsNumber(429)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🐌",
    },
    Badge {
        id: "code_502",
        name: "Bad Gateway",
        desc: "502 \u{2014} the server tripped",
        condition: Cond::Prop(PropCheck::ContainsNumber(502)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "🚪",
    },
    Badge {
        id: "code_503",
        name: "Service Unavailable",
        desc: "503 \u{2014} try again later",
        condition: Cond::Prop(PropCheck::ContainsNumber(503)),
        ep: 40,
        rarity: Rarity::Uncommon,
        icon: "💤",
    },
    // ── New combination badges ─────────────────────────────────────
    Badge {
        id: "fibonacci_lucas",
        name: "Fibonacci-Lucas",
        desc: "In both the Fibonacci and Lucas sequences",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsFibonacci),
            Cond::Prop(PropCheck::IsLucas),
        ]),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🐚🔢",
    },
    Badge {
        id: "mersenne_prime",
        name: "Mersenne Prime",
        desc: "A Mersenne number that's also prime",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsMersenne),
            Cond::Prop(PropCheck::IsPrime),
        ]),
        ep: 300,
        rarity: Rarity::Legendary,
        icon: "🇲🔢",
    },
    Badge {
        id: "kaprekar_palindrome",
        name: "Kaprekar Palindrome",
        desc: "A Kaprekar number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsKaprekar),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 250,
        rarity: Rarity::Epic,
        icon: "✂️🪞",
    },
    Badge {
        id: "happy_harshad",
        name: "Happy Harshad",
        desc: "Both a happy number and a Harshad number",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsHappy),
            Cond::Prop(PropCheck::IsHarshad),
        ]),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "😊➗",
    },
    Badge {
        id: "undulating_prime",
        name: "Undulating Prime",
        desc: "A prime number that undulates between two digits",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsUndulating),
            Cond::Prop(PropCheck::IsPrime),
        ]),
        ep: 200,
        rarity: Rarity::Epic,
        icon: "🌊🔢",
    },
    Badge {
        id: "sphenic_palindrome",
        name: "Sphenic Palindrome",
        desc: "A sphenic number that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsSphenic),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🔺🪞",
    },
    Badge {
        id: "pentagonal_palindrome",
        name: "Pentagonal Palindrome",
        desc: "A pentagonal number that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPentagonal),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "⬠🪞",
    },
    Badge {
        id: "smith_palindrome",
        name: "Smith Palindrome",
        desc: "A Smith number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsSmith),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "🔨🪞",
    },
    Badge {
        id: "all_even_palindrome",
        name: "Even Palindrome",
        desc: "A palindrome made entirely of even digits",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPalindrome),
            Cond::Prop(PropCheck::AllEven),
        ]),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "🪞✌️",
    },
    Badge {
        id: "all_even_happy",
        name: "Happy Even",
        desc: "A happy number with all even digits",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsHappy),
            Cond::Prop(PropCheck::AllEven),
        ]),
        ep: 120,
        rarity: Rarity::Rare,
        icon: "😊✌️",
    },
    Badge {
        id: "deficient_palindrome",
        name: "Deficient Palindrome",
        desc: "A deficient number that's also a palindrome",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsDeficient),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 80,
        rarity: Rarity::Rare,
        icon: "📉🪞",
    },
    Badge {
        id: "pernicious_palindrome",
        name: "Pernicious Palindrome",
        desc: "A pernicious number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsPernicious),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 150,
        rarity: Rarity::Epic,
        icon: "☠️🪞",
    },
    Badge {
        id: "evil_palindrome",
        name: "Evil Palindrome",
        desc: "An evil number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsEvil),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "👿🪞",
    },
    Badge {
        id: "odious_palindrome",
        name: "Odious Palindrome",
        desc: "An odious number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsOdious),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 100,
        rarity: Rarity::Rare,
        icon: "😈🪞",
    },
    Badge {
        id: "munchausen_palindrome",
        name: "Munchausen Palindrome",
        desc: "A Munchausen number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsMunchausen),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🎩🪞",
    },
    Badge {
        id: "dudeney_palindrome",
        name: "Dudeney Palindrome",
        desc: "A Dudeney number that reads the same both ways",
        condition: Cond::All(&[
            Cond::Prop(PropCheck::IsDudeney),
            Cond::Prop(PropCheck::IsPalindrome),
        ]),
        ep: 500,
        rarity: Rarity::Legendary,
        icon: "🧩🪞",
    },
    // ── New digit-sum badges ───────────────────────────────────────
    Badge {
        id: "digit_sum_7",
        name: "Lucky Seven Sum",
        desc: "Digit sum is exactly 7",
        condition: Cond::Prop(PropCheck::DigitSumEq(7)),
        ep: 30,
        rarity: Rarity::Uncommon,
        icon: "7️⃣",
    },
    Badge {
        id: "digit_sum_13",
        name: "Unlucky Sum",
        desc: "Digit sum is exactly 13",
        condition: Cond::Prop(PropCheck::DigitSumEq(13)),
        ep: 40,
        rarity: Rarity::Rare,
        icon: "🍀",
    },
    Badge {
        id: "digit_sum_42",
        name: "The Answer Sum",
        desc: "Digit sum is exactly 42",
        condition: Cond::Prop(PropCheck::DigitSumEq(42)),
        ep: 80,
        rarity: Rarity::Epic,
        icon: "🌍",
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cond::Cond;

    #[test]
    fn no_duplicate_badge_ids() {
        for i in 0..BADGES.len() {
            for j in (i + 1)..BADGES.len() {
                assert_ne!(
                    BADGES[i].id, BADGES[j].id,
                    "duplicate badge id: {}",
                    BADGES[i].id
                );
            }
        }
    }

    #[test]
    fn every_exact_match_badge_has_meme_entry() {
        for badge in BADGES {
            if matches!(badge.condition, Cond::Prop(PropCheck::ContainsNumber(_))) {
                let found = MEME_NUMBERS.iter().any(|m| m.badge_id == badge.id);
                assert!(
                    found,
                    "badge '{}' uses ContainsNumber but has no MemeEntry",
                    badge.id
                );
            }
        }
    }

    #[test]
    fn every_meme_badge_id_matches_a_badge() {
        for meme in MEME_NUMBERS {
            let found = BADGES.iter().any(|b| b.id == meme.badge_id);
            assert!(
                found,
                "MemeEntry '{}' references nonexistent badge id '{}'",
                meme.number, meme.badge_id
            );
        }
    }
}
