pub enum Cond {
    Prop(PropCheck),
    All(&'static [Cond]),
    Any(&'static [Cond]),
    Not(&'static Cond),
}

pub enum PropCheck {
    IsPrime,
    IsPalindrome,
    IsPerfectSquare,
    IsFibonacci,
    IsPowerOfTwo,
    IsTriangular,
    DigitSumGte(u8),
    DigitSumLte(u8),
    DigitSumEq(u8),
    DigitCountEq(u8),
    DigitCountGte(u8),
    DigitCountLte(u8),
    MaxRepeatingGte(u8),
    MaxRepeatingEq(u8),
    MaxAscendingRunGte(u8),
    MaxDescendingRunGte(u8),
    AllSame,
    StrictlyAscending,
    StrictlyDescending,
    HasDouble,
    HasTriple,
    HasQuad,
    HasQuint,
    HasSextuple,
    LeadingZerosGte(u8),
    LeadingZerosEq(u8),
    ContainsNumber(u32),
    IsComposite,
    HasZero,
    IsEven,
    IsOdd,
    IsHarshad,
    HasSeven,
    NoZeros,
    IsPerfectCube,
    IsHappy,
    IsAlternating,
    Has123,
    Has666,
    IsFactorial,
    IsAutomorphic,
    IsArmstrong,
    DigitProductGte(u32),
    DigitSumIsSquare,
    NoRepeats,
    IsEvil,
    IsOdious,
    IsPernicious,
    IsPerfectNum,
    IsAbundant,
    IsDeficient,
    IsPronic,
    IsLucas,
    IsUndulating,
    IsMoran,
    IsSemiprime,
    IsSquarefree,
    IsSmith,
    IsKaprekar,
    IsMunchausen,
    IsMersenne,
    IsPowerOfTen,
    IsSphenic,
    IsDudeney,
    IsPentagonal,
    AllEven,
    AllOdd,
}

pub fn eval(cond: &Cond, props: &crate::props::Props) -> bool {
    match cond {
        Cond::Prop(p) => eval_prop(p, props),
        Cond::All(children) => children.iter().all(|c| eval(c, props)),
        Cond::Any(children) => children.iter().any(|c| eval(c, props)),
        Cond::Not(child) => !eval(*child, props),
    }
}

fn eval_prop(p: &PropCheck, props: &crate::props::Props) -> bool {
    match p {
        PropCheck::IsPrime => props.is_prime,
        PropCheck::IsPalindrome => props.is_palindrome,
        PropCheck::IsPerfectSquare => props.is_perfect_square,
        PropCheck::IsFibonacci => props.is_fibonacci,
        PropCheck::IsPowerOfTwo => props.is_power_of_two,
        PropCheck::IsTriangular => props.is_triangular,
        PropCheck::DigitSumGte(v) => props.digit_sum >= *v,
        PropCheck::DigitSumLte(v) => props.digit_sum <= *v,
        PropCheck::DigitSumEq(v) => props.digit_sum == *v,
        PropCheck::DigitCountEq(v) => props.digit_count == *v,
        PropCheck::DigitCountGte(v) => props.digit_count >= *v,
        PropCheck::DigitCountLte(v) => props.digit_count <= *v,
        PropCheck::MaxRepeatingGte(v) => props.max_repeating >= *v,
        PropCheck::MaxRepeatingEq(v) => props.max_repeating == *v,
        PropCheck::MaxAscendingRunGte(v) => props.max_ascending_run >= *v,
        PropCheck::MaxDescendingRunGte(v) => props.max_descending_run >= *v,
        PropCheck::AllSame => props.all_same,
        PropCheck::StrictlyAscending => props.strictly_ascending,
        PropCheck::StrictlyDescending => props.strictly_descending,
        PropCheck::HasDouble => props.has_double,
        PropCheck::HasTriple => props.has_triple,
        PropCheck::HasQuad => props.has_quad,
        PropCheck::HasQuint => props.has_quint,
        PropCheck::HasSextuple => props.has_sextuple,
        PropCheck::LeadingZerosGte(v) => props.leading_zeros >= *v,
        PropCheck::LeadingZerosEq(v) => props.leading_zeros == *v,
        PropCheck::ContainsNumber(target) => props.contains_number(*target),
        PropCheck::IsComposite => props.is_composite,
        PropCheck::HasZero => props.has_zero,
        PropCheck::IsEven => props.is_even,
        PropCheck::IsOdd => !props.is_even,
        PropCheck::IsHarshad => props.is_harshad,
        PropCheck::HasSeven => props.has_seven,
        PropCheck::NoZeros => props.no_zeros,
        PropCheck::IsPerfectCube => props.is_perfect_cube,
        PropCheck::IsHappy => props.is_happy,
        PropCheck::IsAlternating => props.is_alternating,
        PropCheck::Has123 => props.has_123,
        PropCheck::Has666 => props.has_666,
        PropCheck::IsFactorial => props.is_factorial,
        PropCheck::IsAutomorphic => props.is_automorphic,
        PropCheck::IsArmstrong => props.is_armstrong,
        PropCheck::DigitProductGte(v) => props.digit_product >= *v,
        PropCheck::DigitSumIsSquare => props.digit_sum_is_square,
        PropCheck::NoRepeats => props.no_repeats,
        PropCheck::IsEvil => props.is_evil,
        PropCheck::IsOdious => props.is_odious,
        PropCheck::IsPernicious => props.is_pernicious,
        PropCheck::IsPerfectNum => props.is_perfect_num,
        PropCheck::IsAbundant => props.is_abundant,
        PropCheck::IsDeficient => props.is_deficient,
        PropCheck::IsPronic => props.is_pronic,
        PropCheck::IsLucas => props.is_lucas,
        PropCheck::IsUndulating => props.is_undulating,
        PropCheck::IsMoran => props.is_moran,
        PropCheck::IsSemiprime => props.is_semiprime,
        PropCheck::IsSquarefree => props.is_squarefree,
        PropCheck::IsSmith => props.is_smith,
        PropCheck::IsKaprekar => props.is_kaprekar,
        PropCheck::IsMunchausen => props.is_munchausen,
        PropCheck::IsMersenne => props.is_mersenne,
        PropCheck::IsPowerOfTen => props.is_power_of_ten,
        PropCheck::IsSphenic => props.is_sphenic,
        PropCheck::IsDudeney => props.is_dudeney,
        PropCheck::IsPentagonal => props.is_pentagonal,
        PropCheck::AllEven => props.all_even,
        PropCheck::AllOdd => props.all_odd,
    }
}
