import type { Icon } from "@tabler/icons-react";
import {
  IconAlertTriangle,
  IconAlphabetGreek,
  IconArrowBarDown,
  IconArrowBarUp,
  IconArrowBigDownLines,
  IconArrowBigUpLines,
  IconArrowDown,
  IconArrowNarrowDown,
  IconArrowNarrowUp,
  IconArrowsCross,
  IconArrowsHorizontal,
  IconArrowsLeftRight,
  IconArrowsSort,
  IconArrowsUpDown,
  IconBallBasketball,
  IconBallBowling,
  IconBallFootball,
  IconBarbell,
  IconBatteryCharging,
  IconBellRinging,
  IconBolt,
  IconBook,
  IconBox,
  IconBread,
  IconBuildingStore,
  IconButterfly,
  IconCake,
  IconCalendar,
  IconCar,
  IconChartPie,
  IconChevronDown,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconCircleDotFilled,
  IconCircleHalf,
  IconCircleNumber0,
  IconCircleNumber1,
  IconCircleNumber2,
  IconCircleNumber3,
  IconCircleNumber4,
  IconCircleNumber5,
  IconCircleNumber6,
  IconCircleNumber7,
  IconCircleNumber8,
  IconCircleNumber9,
  IconCircleX,
  IconClock,
  IconClockHour4,
  IconCloud,
  IconCode,
  IconCoffee,
  IconConfetti,
  IconCopy,
  IconCrown,
  IconCube,
  IconDeviceGamepad,
  IconDiamondFilled,
  IconDice,
  IconDice1,
  IconDice3,
  IconDice4,
  IconDice5,
  IconDice6,
  IconDivide,
  IconDoor,
  IconExclamationMark,
  IconEye,
  IconFlag,
  IconFlame,
  IconFlipVertical,
  IconHammer,
  IconHash,
  IconHeart,
  IconHexagon,
  IconHexagonFilled,
  IconHistory,
  IconHourglassLow,
  IconInfinity,
  IconKey,
  IconLemon,
  IconLicense,
  IconLock,
  IconLockSquare,
  IconMask,
  IconMathPi,
  IconMoodAnnoyed,
  IconMoodCry,
  IconMoodHappy,
  IconMoodKid,
  IconMoodSmile,
  IconMoodWink,
  IconMoodWrrr,
  IconMoon,
  IconMovie,
  IconMusic,
  IconNumbers,
  IconPentagon,
  IconPhone,
  IconPlayCard,
  IconPlayerPlay,
  IconPuzzle,
  IconRepeat,
  IconReportMoney,
  IconRipple,
  IconRotate,
  IconRoute,
  IconScissors,
  IconShield,
  IconShieldHalf,
  IconShieldX,
  IconSkull,
  IconSnowflake,
  IconSparkles,
  IconSpiral,
  IconSquare,
  IconSquareRotated,
  IconStack,
  IconSticker,
  IconSum,
  IconTemperature,
  IconThumbUp,
  IconTriangle,
  IconTriangleFilled,
  IconTrophy,
  IconWaveSine,
  IconWorld,
  IconX,
} from "@tabler/icons-react";

export const BADGE_ICONS: Record<string, Icon> = {
  // Math properties
  prime: IconShield,
  palindrome: IconArrowsHorizontal,
  double: IconCopy,
  high_sum: IconArrowBarUp,
  low_sum: IconArrowBarDown,
  perfect_square: IconSquare,
  fibonacci: IconCircle,
  power_of_two: IconBolt,
  triangular: IconTriangle,
  triple: IconDice3,
  ascending_run: IconArrowNarrowUp,
  descending_run: IconArrowNarrowDown,
  short_palindrome_prime: IconHash,
  palindrome_prime: IconArrowsHorizontal,
  quad: IconDice4,
  all_same: IconRepeat,
  strictly_ascending: IconArrowsUpDown,
  strictly_descending: IconArrowsLeftRight,
  digit_sum_54: IconSum,
  leading_zeros_5: IconCircleDashed,
  fibonacci_prime: IconCircleNumber7,
  square_and_triangular: IconSquareRotated,
  quint: IconDice5,
  ascending_5: IconArrowBigUpLines,
  descending_5: IconArrowBigDownLines,
  palindrome_prime_6: IconHash,
  triple_properties: IconTrophy,
  sextuple: IconDice6,
  full_ascending: IconChevronUp,
  full_descending: IconChevronDown,
  zero: IconCircleDot,
  one: IconCircleNumber1,
  answer: IconWorld,
  nice: IconMoodKid,
  blaze_it: IconFlame,
  number_of_the_beast: IconMoodWrrr,
  jackpot: IconDice,
  one_k: IconCircleNumber1,
  leet: IconCode,
  not_found: IconAlertTriangle,
  boobs: IconMoodWink,
  one_hundred_k: IconCircleNumber1,
  consecutive: IconNumbers,
  reverse_consecutive: IconArrowsSort,
  all_ones: IconCircleNumber1,
  all_twos: IconCircleNumber2,
  all_threes: IconCircleNumber3,
  all_fours: IconCircleNumber4,
  all_fives: IconCircleNumber5,
  all_sixes: IconCircleNumber6,
  all_sevens: IconCircleNumber7,
  all_eights: IconCircleNumber8,
  all_nines: IconCircleNumber9,
  one_million: IconCrown,
  pi_approx: IconMathPi,
  e_approx: IconAlphabetGreek,
  nice_blaze: IconFlame,
  emergency: IconBellRinging,
  bond: IconLicense,
  hundred: IconCircleNumber1,
  intro_level: IconBook,
  sequential_123: IconNumbers,
  i_love_you: IconHeart,
  pi_day: IconChartPie,
  love_chinese: IconHeart,
  tr_808: IconMusic,
  lucky_eights: IconCircleNumber8,
  basic_sequence: IconKey,
  programmers_k: IconCode,
  forever: IconInfinity,
  love_forever: IconHeart,
  independence: IconFlag,
  moon_landing: IconMoon,
  big_brother: IconEye,
  party_like: IconConfetti,
  y2k: IconHistory,
  the_year: IconMask,
  the_game: IconDeviceGamepad,
  the_sequel: IconPlayerPlay,
  over_nine_thousand: IconBarbell,
  boobies: IconLemon,
  boobies_flip: IconFlipVertical,
  jenny: IconPhone,
  golden_ratio: IconSpiral,
  composite: IconStack,
  has_zero: IconCircleNumber0,
  even: IconCircleHalf,
  odd: IconCircleDotFilled,
  harshad: IconDivide,
  has_seven: IconCircleNumber7,
  no_zeros: IconCircleX,
  perfect_cube: IconCube,
  happy: IconMoodSmile,
  alternating: IconArrowsCross,
  contains_123: IconHash,
  contains_666: IconSkull,
  factorial: IconExclamationMark,
  automorphic: IconRotate,
  armstrong: IconThumbUp,
  big_product: IconX,
  digit_sum_square: IconSparkles,
  no_repeats: IconSticker,
  prime_plus_even: IconShieldHalf,
  fibonacci_even: IconCircleHalf,
  palindrome_even: IconArrowsHorizontal,
  prime_harshad: IconHash,
  happy_prime: IconMoodHappy,
  cube_palindrome: IconCube,
  murder: IconShieldX,
  ok: IconCircleCheck,
  not_modified: IconBox,
  bad_request: IconAlertTriangle,
  forbidden: IconLock,
  fahrenheit: IconFlame,
  server_error: IconCloud,
  double_nice: IconMoodWink,
  fibonacci_start: IconCircle,
  almost_consecutive: IconNumbers,
  reverse_almost: IconArrowNarrowDown,
  eleet: IconMask,
  descending: IconArrowDown,
  nice_blaze_2: IconFlame,
  five_ones: IconCircleNumber1,
  five_twos: IconCircleNumber2,
  five_threes: IconCircleNumber3,
  five_fours: IconCircleNumber4,
  five_fives: IconCircleNumber5,
  five_sixes: IconCircleNumber6,
  five_sevens: IconCircleNumber7,
  five_eights: IconCircleNumber8,
  five_nines: IconCircleNumber9,
  evil: IconMoodAnnoyed,
  odious: IconMoodCry,
  pernicious: IconSkull,
  perfect_number: IconDiamondFilled,
  abundant: IconArrowBigUpLines,
  deficient: IconArrowBigDownLines,
  pronic: IconSquare,
  lucas: IconCircle,
  undulating: IconWaveSine,
  moran: IconHash,
  semiprime: IconX,
  squarefree: IconSticker,
  smith: IconHammer,
  lucky_prime: IconCircleNumber7,
  evil_prime: IconShieldHalf,
  abundant_prime: IconDiamondFilled,
  semiprime_palindrome: IconArrowsHorizontal,
  happy_semiprime: IconMoodHappy,
  kaprekar: IconScissors,
  munchausen: IconCrown,
  mersenne: IconHexagonFilled,
  power_of_ten: IconCircleNumber0,
  sphenic: IconTriangleFilled,
  dudeney: IconPuzzle,
  pentagonal: IconPentagon,
  all_even: IconCircleHalf,
  all_odd: IconCircleDotFilled,
  bakers_dozen: IconBread,
  catch: IconEye,
  number_23: IconBallBasketball,
  jack_bauer: IconClockHour4,
  perfect_game: IconBallBowling,
  angel: IconCircleNumber3,
  infinity: IconInfinity,
  cloud_nine: IconCloud,
  binary_day: IconCode,
  sweet_sixteen: IconCake,
  comeback: IconBallFootball,
  blackjack: IconPlayCard,
  snake_eyes: IconDice1,
  repeater: IconSparkles,
  triple_twos: IconCircleNumber2,
  half_way: IconBread,
  emergency_eu: IconShield,
  directory: IconBook,
  kia_ora: IconFlag,
  maximum_effort: IconCircleNumber9,
  boiling_point: IconTemperature,
  freezing_point: IconSnowflake,
  speed_limit: IconCar,
  route_66: IconRoute,
  half_life: IconBatteryCharging,
  bit_depth: IconStack,
  thx: IconMovie,
  full_circle: IconRipple,
  days: IconCalendar,
  leap_year: IconButterfly,
  convenience: IconBuildingStore,
  code_401: IconLockSquare,
  code_402: IconReportMoney,
  code_405: IconLock,
  code_418: IconCoffee,
  code_429: IconClock,
  code_502: IconDoor,
  code_503: IconHourglassLow,
  fibonacci_lucas: IconCircle,
  mersenne_prime: IconHexagon,
  kaprekar_palindrome: IconScissors,
  happy_harshad: IconMoodHappy,
  undulating_prime: IconWaveSine,
  sphenic_palindrome: IconTriangleFilled,
  pentagonal_palindrome: IconPentagon,
  smith_palindrome: IconHammer,
  all_even_palindrome: IconArrowsHorizontal,
  all_even_happy: IconMoodHappy,
  deficient_palindrome: IconArrowsHorizontal,
  pernicious_palindrome: IconSkull,
  evil_palindrome: IconMoodAnnoyed,
  odious_palindrome: IconMoodCry,
  munchausen_palindrome: IconCrown,
  dudeney_palindrome: IconPuzzle,
  digit_sum_7: IconCircleNumber7,
  digit_sum_13: IconCircleNumber1,
  digit_sum_42: IconWorld,
};